window.PUMP_DEMO_DATA = {
  meta: {
    title: "输油泵智能运维助手",
    subtitle: "长岭站 P-1 疑似不对中诊断处置闭环",
    batch: "PUMP-DEMO-202607",
    clock: "2026-07-22 16:31",
    sourceNote: "业务素材抽取 + 结构化演示构造",
  },
  scenes: [
    { key: "event", label: "主事件", node: "异常事件" },
    { key: "diagnosis", label: "诊断证据", node: "诊断输出" },
    { key: "knowledge", label: "复核依据", node: "专家复核" },
    { key: "workorder", label: "处置复测", node: "处置票卡" },
    { key: "report", label: "报告复用", node: "报告复用" },
  ],
  assetImages: {
    pointMap: "media/point-map.jpg",
    laserBefore: "media/laser-before.jpg",
    laserAfter: "media/laser-after.jpg",
    fieldWork: "media/field-work.jpg",
    fieldClose: "media/field-close.jpg",
  },
  assets: [
    {
      id: "CL-P1",
      name: "P-1 输油泵机组",
      station: "长岭站",
      role: "首次闭环主线",
      pumpModel: "KSY900-225",
      motorModel: "YB2-560M2-2W",
      speedRpm: 3000,
      rotatingFrequencyHz: 50,
      state: "关注",
      runtimeSource: "结构化演示数据（映射 IMS 模块，非实时接入）",
      basisSource: "P1检测报告抽取",
    },
    {
      id: "CL-P2",
      name: "P-2 输油泵机组",
      station: "长岭站",
      role: "复用验证样例",
      pumpModel: "同型主输泵",
      motorModel: "同型电机",
      speedRpm: 3000,
      rotatingFrequencyHz: 50,
      state: "待复核",
      runtimeSource: "结构化演示数据（映射 IMS 模块，非实时接入）",
      basisSource: "演示构造",
    },
  ],
  event: {
    id: "WE-CL-P1-001",
    assetId: "CL-P1",
    title: "长岭站 P-1 输油泵机组振动趋势异常",
    grade: "关注级",
    currentNode: "warning",
    trigger: "泵驱动端垂直振动进入 80% 演示预警线，并命中不对中特征证据。",
    detectedAt: "2026-07-22 15:42",
    runtimeSource: "结构化演示数据（映射 IMS 模块，非实时接入）",
    basisSource: "P1检测报告抽取 + 演示构造",
    summary: [
      { label: "当前对象", value: "长岭站 P-1" },
      { label: "异常测点", value: "泵驱动端垂直" },
      { label: "诊断建议", value: "疑似不对中" },
      { label: "下一动作", value: "提交专家复核" },
    ],
  },
  capabilityMap: [
    {
      capability: "远程监测诊断",
      proof: "趋势、阈值、频谱、相位共同支撑 P-1 关注级诊断事件。",
      demoPart: "主事件入口 / 诊断证据",
      boundary: "不接真实实时监测接口。",
    },
    {
      capability: "三级体系",
      proof: "诊断专家复核、区域监视推进、作业区反馈在同一闭环中分工呈现。",
      demoPart: "复核依据 / 处置复测",
      boundary: "不模拟真实组织审批。",
    },
    {
      capability: "知识沉淀",
      proof: "P-1 报告确认和知识审核后，P-2 相似异常命中 P-1 案例。",
      demoPart: "报告复用",
      boundary: "不接真实 RAG 或知识图谱。",
    },
  ],
  measurementPoints: [
    { id: "M-NDE-H", name: "电机非驱动端水平", component: "电机", direction: "水平", x: 70, y: 48, status: "normal" },
    { id: "M-DE-H", name: "电机驱动端水平", component: "电机", direction: "水平", x: 55, y: 52, status: "watch" },
    { id: "P-DE-V", name: "泵驱动端垂直", component: "泵", direction: "垂直", x: 30, y: 45, status: "active" },
    { id: "P-DE-H", name: "泵驱动端水平", component: "泵", direction: "水平", x: 35, y: 54, status: "watch" },
    { id: "P-FND-F", name: "泵基础 F", component: "基础", direction: "基础", x: 43, y: 76, status: "active" },
  ],
  thresholds: {
    metric: "velocity_rms_mm_s",
    unit: "mm/s",
    gradeBMax: 4.5,
    stopValue: 7.1,
    warningValue: 5.68,
    note: "停机值 80% 作为首版演示预警线；B 级阈值需业务确认。",
  },
  trend: {
    title: "泵驱动端垂直振动趋势",
    unit: "mm/s",
    points: [
      { t: "07-18 08:00", y: 2.62, source: "P1检测报告抽取" },
      { t: "07-19 08:00", y: 3.18, source: "演示构造" },
      { t: "07-20 08:00", y: 4.12, source: "演示构造" },
      { t: "07-21 08:00", y: 5.08, source: "演示构造" },
      { t: "07-22 15:42", y: 5.82, source: "演示构造" },
      { t: "复测", y: 1.8, source: "业务待补 + 演示构造" },
    ],
  },
  spectrum: {
    pointId: "M-NDE-H",
    title: "频谱特征",
    peaks: [
      { harmonic: "1X", hz: 49.7, amplitude: 0.42, label: "转频成分" },
      { harmonic: "2X", hz: 100.3, amplitude: 0.91, label: "不对中特征" },
      { harmonic: "6X", hz: 298.8, amplitude: 0.34, label: "叶片通过频率" },
    ],
  },
  phases: [
    {
      id: "PH-P1-MOTOR-PUMP-DE",
      pair: "电机驱动端 H / 泵驱动端 H",
      delta: -81.06,
      correlation: 0.97,
      verdict: "相位差接近不对中特征",
    },
    {
      id: "PH-P1-MOTOR-DE-HV",
      pair: "电机驱动端 H / V",
      delta: 150.08,
      correlation: 0.99,
      verdict: "同端水平垂直相位差明显",
    },
  ],
  diagnosis: {
    id: "DR-CL-P1-001",
    result: "疑似不对中",
    severity: "关注",
    evidenceTags: ["2X频谱", "相位差异常", "基础振动偏大"],
    actions: ["检查对中", "检查地脚螺栓", "检查管道固定", "检查工况点"],
    explanation: "趋势进入关注区，2X 频谱成分突出，电机与泵驱动端相位差异常，建议按疑似不对中进入专家复核。",
  },
  knowledgeItems: [
    {
      id: "KI-WC-ALIGN-001",
      type: "作业卡",
      title: "输油泵对中作业标准模板卡",
      reason: "建议动作包含“检查对中”。",
      basisSource: "P1作业卡抽取",
    },
    {
      id: "KI-RULE-MISALIGN-001",
      type: "专家规则",
      title: "不对中诊断专家规则",
      reason: "2X 频谱 + 相位差异常 + 基础振动偏大。",
      basisSource: "P1检测报告抽取 + 演示构造",
    },
    {
      id: "KI-CASE-VIB-001",
      type: "历史案例",
      title: "同类泵振动异常排查案例",
      reason: "同类动设备、相似证据标签。",
      basisSource: "历史报告抽取 + 演示构造",
    },
    {
      id: "KI-TEMPLATE-REPORT-001",
      type: "报告模板",
      title: "维修报告六段式模板",
      reason: "处置闭环需要形成标准报告草稿。",
      basisSource: "历史报告抽取 + 业务待补",
    },
  ],
  workOrder: {
    id: "WO-CL-P1-001",
    title: "P-1 疑似不对中处置票卡草稿",
    roles: ["检修负责人", "检修作业人员", "运行监护人"],
    permits: ["作业许可", "专项许可", "JSA"],
    tools: ["激光对中仪", "调整垫片", "扳手", "测振仪"],
    steps: [
      "记录检修前振动值和轴承温度",
      "执行能量隔离和现场安全确认",
      "使用激光对中仪测量电机与泵轴线",
      "调整电机地脚垫片并复测",
      "复测振动、温度和对中仪读数",
      "恢复备用并提交处置反馈",
    ],
  },
  feedback: {
    beforeVibration: 5.82,
    afterVibration: 1.8,
    adjustment: "调整电机地脚垫片后复测，水平和垂直偏差收敛。",
    acceptance: "复测振动回落至关注线以下，运行负责人确认恢复备用。",
    basisSource: "演示构造 + 业务待补",
  },
  report: {
    title: "长岭站 P-1 输油泵疑似不对中诊断与对中处置报告",
    sections: [
      { title: "事件概况", text: "P-1 泵驱动端垂直振动趋势进入关注区，形成关注级诊断事件。" },
      { title: "诊断依据", text: "趋势、2X 频谱、相位差和基础振动共同支撑疑似不对中判断。" },
      { title: "处置过程", text: "专家复核后调取对中作业标准模板卡，生成演示态处置票卡并完成现场反馈。" },
      { title: "复测结论", text: "处置后振动由 5.82 mm/s 回落至 1.80 mm/s，演示口径下满足验收。" },
      { title: "经验标签", text: "不对中、2X频谱、相位差异常、基础振动偏大、对中复测。" },
    ],
  },
  caseEntry: {
    id: "CASE-CL-P1-ALIGN-001",
    title: "长岭站 P-1 输油泵不对中诊断与对中处置案例",
    tags: ["不对中", "2X频谱", "相位差异常", "基础振动", "对中作业"],
    reviewer: "知识审核人",
    suggestion: "下次同类异常优先检查对中，并调取输油泵对中作业标准模板卡。",
  },
  reuse: {
    eventId: "WE-CL-P2-REUSE-001",
    assetId: "CL-P2",
    title: "长岭站 P-2 相似振动异常复用验证",
    matchedCaseId: "CASE-CL-P1-ALIGN-001",
    reasons: ["2X频谱", "相位差异常", "基础振动偏大"],
    recommendation: "优先检查对中情况，调取输油泵对中作业标准模板卡，仍需专家复核和现场安全确认。",
  },
};
