window.PUMP_DEMO_DATA = {
  meta: {
    title: "输油泵智能运维助手",
    subtitle: "长岭站 P-1 疑似不对中诊断处置闭环",
    batch: "PUMP-DEMO-202607",
    clock: "2026-07-22 16:31",
    boundary: "结构化演示数据驱动；不接真实系统、不训练真实模型、不替代专家。",
  },
  scenes: [
    { key: "overview", label: "任务总览", node: "部位态势" },
    { key: "workbench", label: "诊断工作台", node: "模型证据" },
    { key: "confirm", label: "专家复核", node: "知识规范" },
    { key: "treatment", label: "处置闭环", node: "票卡复测" },
    { key: "archive", label: "报告归档", node: "案例复用" },
  ],
  flowSteps: [
    { key: "task", label: "任务总览" },
    { key: "workbench", label: "诊断工作台" },
    { key: "trend", label: "时序模型" },
    { key: "vision", label: "视觉模型" },
    { key: "agent", label: "Agent 问答" },
    { key: "confirm", label: "专家确认" },
    { key: "treatment", label: "处置复测" },
    { key: "archive", label: "报告归档" },
    { key: "reuse", label: "二次命中" },
  ],
  media: {
    pointMap: "media/point-map.jpg",
    laserBefore: "media/laser-before.jpg",
    laserAfter: "media/laser-after.jpg",
    fieldWork: "media/field-work.jpg",
    fieldClose: "media/field-close.jpg",
  },
  task: {
    batch: "PUMP-DEMO-202607",
    title: "长岭站 P-1 输油泵机组关注级诊断任务",
    note: "沿用巡检 v3 的演示骨架：总览大屏锁定对象，工作台并联查看时序模型、视觉模型、知识规范和 Agent 建议，人工确认后归档并支持二次命中。",
    rows: [
      ["站场", "长岭站"],
      ["对象", "P-1 输油泵机组"],
      ["事件", "疑似不对中"],
      ["等级", "关注级"],
    ],
    metrics: [
      { label: "异常部位", value: "3", unit: "个" },
      { label: "关注部位", value: "1", unit: "个" },
      { label: "知识命中", value: "4", unit: "项" },
      { label: "复用样例", value: "P-2", unit: "" },
    ],
  },
  pumpUnits: [
    { id: "P-1", name: "P-1 主输泵", status: "异常", load: "84%", vibration: "5.82 mm/s", temp: "68.4°C" },
    { id: "P-2", name: "P-2 主输泵", status: "待复核", load: "76%", vibration: "4.96 mm/s", temp: "63.1°C" },
    { id: "P-3", name: "P-3 备用泵", status: "正常", load: "0%", vibration: "0.42 mm/s", temp: "32.8°C" },
    { id: "P-4", name: "P-4 主输泵", status: "正常", load: "71%", vibration: "2.18 mm/s", temp: "58.6°C" },
  ],
  parts: [
    {
      id: "pump-body",
      label: "泵体",
      short: "泵体",
      status: "ok",
      badge: "工况稳定",
      component: "泵壳 / 蜗壳",
      position: { x: 250, y: 275 },
      summary: "出口压力和工况波动稳定，当前不作为主要异常源。",
      checkItem: "泵体出口压力与运行工况",
      trend: {
        title: "泵体出口压力趋势",
        unit: "MPa",
        threshold: 6.8,
        points: [["07-18", 6.35], ["07-19", 6.41], ["07-20", 6.38], ["07-21", 6.45], ["07-22", 6.42]],
        alert: "压力波动约 1.8%，未见工况突变。",
      },
      vision: {
        title: "泵体点位与管线状态",
        src: "pointMap",
        caption: "点位图用于定位泵体、进出口压力和周边测点。",
        finding: "视觉证据未指向泵体工况异常。",
      },
      evidence: ["出口压力 6.42 MPa", "压力波动 1.8%", "未见工况突变证据"],
      agent: "泵体工况可作为对照项，当前不建议把泵体作为主故障源。",
    },
    {
      id: "seal",
      label: "密封",
      short: "密封",
      status: "ok",
      badge: "排除项",
      component: "机械密封",
      position: { x: 360, y: 185 },
      summary: "机械密封未见泄漏和温升异常，作为排除项记录。",
      checkItem: "机械密封泄漏和温升观察",
      trend: {
        title: "密封泄漏观察记录",
        unit: "级",
        threshold: 1,
        points: [["07-18", 0], ["07-19", 0], ["07-20", 0], ["07-21", 0], ["07-22", 0]],
        alert: "连续观察为 0 级，未触发泄漏预警。",
      },
      vision: {
        title: "现场密封检查照片",
        src: "fieldClose",
        caption: "现场近景用于辅助确认密封、连接和周边状态。",
        finding: "未见明显泄漏痕迹，保留人工复核项。",
      },
      evidence: ["泄漏观察正常", "未见异常温升", "不指向密封故障"],
      agent: "密封部位暂不作为主因，但建议在现场处置票卡中保留复核项。",
    },
    {
      id: "front-bearing",
      label: "泵驱动端轴承",
      short: "轴承",
      status: "danger",
      badge: "时序预警",
      component: "泵驱动端轴承",
      position: { x: 430, y: 280 },
      summary: "泵驱动端垂直振动进入关注区，是本次事件的直接触发测点。",
      checkItem: "泵驱动端轴承垂直振动",
      trend: {
        title: "泵驱动端轴承垂直振动趋势",
        unit: "mm/s",
        threshold: 5.68,
        stop: 7.1,
        points: [["07-18", 2.62], ["07-19", 3.18], ["07-20", 4.12], ["07-21", 5.08], ["07-22", 5.82]],
        alert: "最新值 5.82 mm/s，超过 80% 演示预警线。",
      },
      vision: {
        title: "泵驱动端点位图",
        src: "pointMap",
        caption: "点位图用于定位 P-DE-V、P-DE-H 和基础测点。",
        finding: "视觉模型提示需要补充轴承座和联轴器近景。",
      },
      evidence: ["5 日内由 2.62 升至 5.82 mm/s", "超过 80% 演示预警线", "1X/2X 成分同步抬升"],
      agent: "建议把轴承振动与联轴器相位差联判，优先复核对中和轴承座状态。",
    },
    {
      id: "coupling",
      label: "联轴器",
      short: "联轴器",
      status: "danger",
      badge: "核心异常",
      component: "联轴器 / 中间节",
      position: { x: 555, y: 280 },
      summary: "联轴器两侧相位差异常，结合 2X 频谱和基础振动，是疑似不对中的核心入口。",
      checkItem: "联轴器两侧相位和对中状态",
      trend: {
        title: "联轴器相位偏差趋势",
        unit: "°",
        threshold: 70,
        stop: 100,
        points: [["07-18", 24], ["07-19", 38], ["07-20", 52], ["07-21", 68], ["07-22", 81]],
        alert: "相位偏差 81°，命中疑似不对中特征。",
      },
      vision: {
        title: "激光对中仪调整前后",
        src: "laserBefore",
        compareSrc: "laserAfter",
        caption: "对中仪图片用于演示视觉证据与处置复测的关联。",
        finding: "调整前后读数可作为复检和报告归档证据。",
      },
      evidence: ["相位差 -81.06° / r=0.97", "2X 成分突出", "与基础振动偏大并发"],
      agent: "建议进入专家复核，停机窗口内执行激光对中复核，并联动检查地脚螺栓。",
    },
    {
      id: "motor",
      label: "电机",
      short: "电机",
      status: "warn",
      badge: "同步抬升",
      component: "电机驱动端",
      position: { x: 720, y: 275 },
      summary: "电机侧振动随泵驱动端同步抬升，暂不作为首要故障源。",
      checkItem: "电机驱动端水平振动",
      trend: {
        title: "电机驱动端水平振动趋势",
        unit: "mm/s",
        threshold: 5.68,
        points: [["07-18", 2.38], ["07-19", 2.74], ["07-20", 3.21], ["07-21", 3.76], ["07-22", 4.18]],
        alert: "电机侧同步抬升，但未达到主触发阈值。",
      },
      vision: {
        title: "现场电机侧检查",
        src: "fieldWork",
        caption: "现场图用于确认电机侧和联轴器作业位置。",
        finding: "需与联轴器对中复核结果联判。",
      },
      evidence: ["驱动端水平 4.18 mm/s", "低于主异常测点", "与泵侧存在同步关系"],
      agent: "电机侧作为关联证据，不建议单独形成电机故障结论。",
    },
    {
      id: "base",
      label: "底座",
      short: "底座",
      status: "danger",
      badge: "基础振动",
      component: "底座 / 地脚",
      position: { x: 470, y: 410 },
      summary: "基础振动偏大，与不对中证据共同出现，需要检查地脚和底座刚性。",
      checkItem: "底座基础振动和地脚状态",
      trend: {
        title: "底座基础振动趋势",
        unit: "mm/s",
        threshold: 3,
        stop: 4.5,
        points: [["07-18", 1.12], ["07-19", 1.48], ["07-20", 2.05], ["07-21", 2.84], ["07-22", 3.36]],
        alert: "基础振动 3.36 mm/s，超过关注线。",
      },
      vision: {
        title: "现场基础和地脚复核",
        src: "fieldWork",
        caption: "现场图用于定位底座、地脚和作业空间。",
        finding: "建议补拍地脚螺栓和垫片细节。",
      },
      evidence: ["F 点基础振动偏大", "与联轴器相位异常并发", "可能放大轴系振动"],
      agent: "处置票卡中应同步纳入地脚螺栓、底座垫片和管道约束检查。",
    },
  ],
  knowledgeHits: [
    { type: "作业卡", title: "输油泵对中作业标准模板卡", reason: "建议动作包含检查对中", source: "P1/04-ZLMI400 对中作业卡" },
    { type: "专家规则", title: "不对中诊断专家规则", reason: "2X 频谱 + 相位差异常 + 基础振动偏大", source: "检测报告抽取 + 演示构造" },
    { type: "历史案例", title: "同类泵振动异常处置案例", reason: "同型主输泵、相似证据标签", source: "P2 历史停泵报告" },
    { type: "报告模板", title: "维修报告六段式模板", reason: "事件、证据、处置、复测、经验标签", source: "历史报告抽取" },
  ],
  workOrder: {
    id: "WO-CL-P1-001",
    title: "P-1 疑似不对中处置票卡草稿",
    steps: ["记录处置前振动值和轴承温度", "执行能量隔离和现场安全确认", "使用激光对中仪复核轴线", "调整电机地脚垫片并复测", "检查地脚螺栓和管道约束", "恢复备用并提交反馈"],
    roles: ["诊断专家", "区域监视中心", "作业区检修人员", "运行监护人"],
  },
  report: {
    title: "长岭站 P-1 输油泵疑似不对中诊断与处置报告",
    sections: [
      ["事件概况", "P-1 泵驱动端轴承振动趋势进入关注区，形成关注级诊断事件。"],
      ["模型证据", "时序模型提示振动和相位趋势异常，视觉模型要求补充联轴器和底座关键帧。"],
      ["专家确认", "专家确认按疑似不对中进入处置，知识库命中对中作业卡和专家规则。"],
      ["处置复测", "对中调整后振动由 5.82 mm/s 回落至 1.80 mm/s，演示口径下满足验收。"],
      ["经验沉淀", "沉淀为 P-1 不对中处置案例，用于 P-2 相似异常复用。"],
    ],
  },
  reuse: {
    title: "长岭站 P-2 相似振动异常",
    matchedCase: "CASE-CL-P1-ALIGN-001",
    reasons: ["2X频谱", "相位差异常", "基础振动偏大"],
    agent: "Agent 命中 P-1 已归档案例，建议优先复核对中并调取输油泵对中作业模板卡。",
  },
  caseKnowledge: {
    schemaVersion: 1,
    unitId: "P-1",
    partId: "coupling",
    caseId: "CASE-CL-P1-ALIGN-001",
    title: "长岭站 P-1 输油泵不对中处置案例",
    firstPass: {
      label: "当前诊断",
      summary: "Agent 围绕 P-1 联轴器疑似不对中事件，综合时序趋势、视觉/数据证据、专家规则和对中作业卡给出复核建议。",
      sources: [
        { text: "P-1 联轴器相位偏差 81°", type: "current" },
        { text: "P-DE-V 振动 5.82 mm/s", type: "current" },
        { text: "2X 频谱成分突出", type: "current" },
        { text: "激光对中仪调整前图", type: "current" },
        { text: "不对中诊断专家规则", type: "standard" },
        { text: "输油泵对中作业标准模板卡", type: "standard" },
      ],
      facts: [
        "对象: 长岭站 P-1 主输泵",
        "事件: 关注级疑似不对中",
        "主触发: 泵驱动端轴承垂直振动升至 5.82 mm/s",
        "核心证据: 联轴器两侧相位差异常且 2X 成分突出",
        "并发证据: 底座基础振动偏大，可能放大轴系振动",
        "排除项: 泵体压力稳定，机械密封未见泄漏和异常温升",
      ],
      questions: [
        {
          q: "为什么优先判断为不对中？",
          a: "P-1 联轴器相位偏差达到 81°，同时 2X 频谱突出、泵驱动端振动升至 5.82 mm/s，并伴随基础振动偏大，符合不对中规则的组合特征。Agent 只能给出疑似结论，仍需专家复核和现场复测确认。",
        },
        {
          q: "现场复核优先看什么？",
          a: "优先复核联轴器两侧相位、激光对中读数、泵驱动端轴承振动和底座地脚状态；同时检查管道约束，避免把基础或管线约束造成的放大效应误判为单点故障。",
        },
        {
          q: "当前能否直接生成维修结论？",
          a: "不能。当前证据只支持进入专家复核和处置票卡草稿，是否确认不对中、继续观察或排除误报，必须由专家结合停机窗口、现场读数和复测结果确认。",
        },
        {
          q: "如果先继续观察，需要观察什么？",
          a: "观察窗口内重点看相位差、2X 成分、P-DE-V 振动和 F 点基础振动是否继续抬升；如果趋势继续恶化，应升级为现场重点复核。",
        },
      ],
    },
    archivedCase: {
      label: "已归档案例",
      summary: "专家确认 P-1 疑似不对中并完成处置复测，报告摘要、作业票卡和案例标签沉淀为后续相似异常的知识来源。",
      sources: [
        { text: "专家结论: 确认不对中", type: "archive" },
        { text: "处置票卡 WO-CL-P1-001", type: "archive" },
        { text: "复测结果 5.82 -> 1.80 mm/s", type: "archive" },
        { text: "维修报告归档", type: "archive" },
        { text: "案例标签: 2X频谱 / 相位差 / 基础振动", type: "archive" },
      ],
      facts: [
        "案例编号: CASE-CL-P1-ALIGN-001",
        "对象: 长岭站 P-1 / 联轴器 / 泵驱动端轴承",
        "触发: 相位偏差 81°、2X 频谱突出、P-DE-V 振动 5.82 mm/s",
        "处置: 执行激光对中复核，调整电机地脚垫片并检查管道约束",
        "复测: 振动由 5.82 mm/s 回落至 1.80 mm/s，作为报告归档证据",
        "边界: 后续只能复用证据项、处置清单和报告结构，不能直接沿用 P-1 结论",
      ],
    },
    secondPass: {
      label: "命中历史案例",
      summary: "Agent 仍围绕 P-2 当前振动异常回答，但可额外引用 P-1 已归档案例，使复核重点、作业卡选择和报告结构更有上下文。",
      sources: [
        { text: "P-2 当前 2X 频谱疑点", type: "current" },
        { text: "P-2 当前相位差异常", type: "current" },
        { text: "P-2 当前基础振动偏大", type: "current" },
        { text: "不对中诊断专家规则", type: "standard" },
        { text: "历史案例 CASE-CL-P1-ALIGN-001", type: "case" },
        { text: "P-1 对中处置票卡和复测报告", type: "case" },
      ],
      facts: [
        "当前对象: 长岭站 P-2 主输泵",
        "命中原因: 与 P-1 共享 2X频谱、相位差异常、基础振动偏大三类标签",
        "参考案例: CASE-CL-P1-ALIGN-001",
        "建议入口: 优先复核对中状态、泵驱动端轴承和底座地脚",
        "需重新确认: P-2 当前负荷、测点趋势、现场照片和专家结论",
        "边界: P-2 不能直接沿用 P-1 的不对中结论或复测结果",
      ],
      questions: [
        {
          q: "P-2 和 P-1 为什么相似？",
          a: "相似点是两者都出现 2X 频谱突出、相位差异常和基础振动偏大的组合标签，并且对象同为长岭站主输泵机组。不同点仍要结合 P-2 当前负荷、现场照片、轴承温度和复测数据确认。",
        },
        {
          q: "本次复核重点是否变化？",
          a: "基础复核重点仍是联轴器对中、泵驱动端轴承和底座地脚。因为命中 P-1 案例，建议额外对比 P-1 处置前后读数、地脚垫片调整记录和管道约束检查项，确认 P-2 是否重复出现同类模式。",
        },
        {
          q: "P-1 哪些处置经验可以复用？",
          a: "可以复用对中作业模板卡、复测指标清单、现场照片要求、报告六段式结构和案例标签；但 P-2 是否停机、是否调整地脚垫片，必须依据本轮专家复核结论决定。",
        },
        {
          q: "能否直接沿用 P-1 的维修结论？",
          a: "不能。历史案例只增强解释和复核路径，不能替代 P-2 的现场确认。本次结论必须基于 P-2 当前时序、视觉/数据证据和人工复核结果重新生成。",
        },
        {
          q: "如果 P-2 趋势继续抬升，建议怎么处理？",
          a: "建议从观察升级为现场重点复核，并调取输油泵对中作业模板卡；若 P-2 复测也出现相位异常和振动回落证据，再归档为新的相似处置案例。",
        },
      ],
    },
  },
};
